### ISSUE TITLE
Update actor information isn't working

### ISSUE THREAD

**Issue by jasny** [ltonetwork/workflow-engine#26]
An update instruction on an actor doesn't update the actor properties.

Please make sure that the following works. First via a flow-test and then via the livecontracts-tester.

```yaml
$schema: "https://specs.livecontracts.io/v0.2.0/scenario/schema.json#"
title: A proper introduction

actors:
  initiator:
    $schema: "http://json-schema.org/schema#"
    title: Initiator
    type: object
    properties:
      name:
        type: string
      organization:
        type: string

actions:
  introduction:
    actor: initiator
    update:
      select: actors.initiator

states:
  initial:
    action: introduction
    transition: :success
```

For `lctest`;

```
Feature: Test update user

  Background:
    Given a chain is created by "Joe"
    Given "Joe" creates the "main" process using the "handshake" scenario
    And   "Joe" is the "initiator" actor of the "main" process

  Scenario:
    When "Joe" runs the "introduce" action of the "main" process with:
      | name         | Joe Smith     |
      | organization | LTO Network   |
    Then the "initiator" actor of the "main" process has:
      | name         | Joe Smith     |
      | organization | LTO Network   |
    And the "main" process is completed
```
