### ISSUE TITLE
Update instruction as string (pretty scenario)

### ISSUE THREAD

**Issue by jasny** [ltonetwork/workflow-engine#27]
Allow an update-instruction to be defined as a string, representing `select`. The `data` and `projection` properties should be considered `null`.

This should happen on pretty json for the scenario and also allowed as input.

---

```
update:
  select: actors.initiator
```
Would be reduced to
```
update: actors.initiator
```

---

```
update:
  - select: assets.client_info
  - select: actors.initiator
    projection: "{ id: uuid }"
```
Would be reduced to
```
update:
  - assets.client_info
  - select: actors.initiator
    projections: "{ id: uuid }"
```
