### ISSUE TITLE
current.actor in action condition

### ISSUE THREAD

**Issue by jasny** [ltonetwork/workflow-engine#35]
Normally `current.actor` isn't available until the action is performed, as the actor isn't known yet. Add a special case for the action condition, allowing the use of `current.actor`.

Process the condition (which is typically a data instruction) for each actor that's allowed to perform the action, setting `current.actor`.

If no actors are allowed to perform the action, the action isn't allowed. In that case, remove it from `current.actions`. Otherwise, modify the `actors` property of the action to the actors that are allowed to perform the action.

**Comment by jasny** [comment]
```yaml
actors:
  initiator:
    $schema: "http://json-schema.org/schema#"
    title: Initiator
    type: object
    properties:
      name:
        type: string
      organization:
        type: string
  recipient:
    $schema: "http://json-schema.org/schema#"
    title: Recipient
    type: object
    properties:
      name:
        type: string
      organization:
        type: string

actions:
  introduce:
    actors:
      - initiator
      - recipient
    condition: !eval current.actor.name == null
    update: current.actor

states:
  initial:
    action: introduce
    transition: wait_on_recipient
  wait_on_recipient:
    action: introduce
    transition: :success
```

```
Feature: Two actors meet at a conference and exchange information.

  Background:
    Given a chain is created by "Joe"
    Given "Joe" creates the "main" process using the "condition" scenario
    And   "Joe" is the "initiator" actor of the "main" process
    And   "Jane" is the "recipient" actor of the "main" process

  Scenario:
    When "Joe" runs the "introduce" action of the "main" process with:
      | name         | Joe Smith     |
      | organization | LTO Network   |
    Then the "initiator" actor of the "main" process has:
      | name         | Joe Smith     |
      | organization | LTO Network   |
    And the "main" process is in the "wait_on_recipient" state
    
    When "Jane" runs the "introduce" action of the "main" process with:
      | name         | Jane Wong     |
      | organization | Acme Inc      |
    Then the "recipient" actor of the "main" process has:
      | name         | Jane Wong     |
      | organization | Acme Inc      |
    And the "main" process is completed
```
